// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Url = require("../src/Url.bs.js");

var url = Url.fromString(undefined, "https://user:pass@wat.com:443/wat?wat=2#wat");

console.log(url);

var str = Url.toString(url);

console.log(str);

exports.url = url;
exports.str = str;
/* url Not a pure module */
